name: pnpm test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm test
